#!/bin/bash


for k in {1024,16384,262144,1048576,4194304,10240000}
do
for i in {32,64,128,256,512,1024}
do
  echo $k
  g++ -DNUM_ELEMENTS=$k -DLOCAL_SIZE=$i -o proj part3.cpp /scratch/Paige/parallelPrograming/project5/libOpenCL.so -lm -fopenmp
  ./proj
done
done
