#!/bin/bash


for k in {1024,10240,102400,1024000,10240000}
do
for i in {32,64,128,256,512,1024}
do
  echo $k
  g++ -DNUM_ELEMENTS=$k -DLOCAL_SIZE=$i -o proj part2.cpp /scratch/Paige/parallelPrograming/project5/libOpenCL.so -lm -fopenmp
  ./proj
done
done
